name: flutter_architecture_blueprint
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  intl:

  clock:
  collection:
  uuid:
  rxdart:
  flutter_hooks:
  hooks_riverpod:
  riverpod_annotation:
  freezed:
  freezed_annotation:
  json_annotation:

  shared_preferences:

  auto_route:
  gap:
  sliver_tools:
  device_preview:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  build_runner:
  json_serializable:
  riverpod_generator:
  auto_route_generator:

  fake_async:

flutter:
  uses-material-design: true
